### ISSUE TITLE
Consignes1

### ISSUE THREAD

**Issue by sabaly** [Amycolle/diangar-sabaly#1]
@Amycolle Salut, ton objectif sera de reproduire le modèle suivant : 

- Grand écran

![image](https://user-images.githubusercontent.com/45306688/81025014-cf0f9480-8e64-11ea-9e44-f37b864554c0.png)

- Petit écran
![image](https://user-images.githubusercontent.com/45306688/81025088-fbc3ac00-8e64-11ea-86c8-dc42f091e5b9.png)

Voilà

**Comment by Amycolle** [comment]
D'accord inchallah je le termine puis je te le renvoie

**Comment by sabaly** [comment]
@Amycolle Parfait... tu l'as bienfait
